###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: ipresence-test-redis

    mysql:
      image: mysql:8.0
      container_name: ipresence-test-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=iPresence-test
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: ipresence-test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      environment:
       XDEBUG_CONFIG: remote_host=host.docker.internal

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ipresence-test-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/xdebug.ini:/etc/php/7.4/fpm/conf.d/xdebug.ini

